---
services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.38
    hostname: ign-tag-ci-cd
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
      - ./third-party-modules:/modules
      - ./tags:/tags
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: ign-tag-ci-cd
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: ign-tag-ci-cd.localtest.me
    labels:
      traefik.enable: "true"
      traefik.hostname: "ign-tag-ci-cd"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
